### ISSUE TITLE
NUC980 constantly restarting

### ISSUE THREAD

**Issue by anton7191** [OpenNuvoton/NUC980_NuWriter_CMD#10]
I was programming dev board NK-NUC980 V1.1 using NUC980_NuWriter_CMD. 
My run.ini  file following:
[run.zip](https://github.com/OpenNuvoton/NUC980_NuWriter_CMD/files/6854567/run.zip)
Image, u-boot.bin, u-boot-spl.bin files were downloads with site nuvoton ():
https://www.nuvoton.com/resource-download.jsp?tp_GUID=SW1820200909165814

And my env.txt file looks like 
[env.zip](https://github.com/OpenNuvoton/NUC980_NuWriter_CMD/files/6854649/env.zip)

And I had shown that my controller constantly restart.
![photo_2021-07-21_12-45-52](https://user-images.githubusercontent.com/37999474/126468981-24ce2c75-3d03-4dae-a867-f465ad866490.jpg)

I don't know what to do with the problems. Help me please

**Comment by yachen** [comment]
You probably enabled WDT by power on setting. Please check if PG3 is pull low (disable WDT after power on) during bootup.

**Comment by anton7191** [comment]
Thank you very much for quickly answer. I disable WDT (sw2.4) and My program has loaded and stop on this. Is it normal?
![photo_2021-07-21_13-50-49](https://user-images.githubusercontent.com/37999474/126477291-2bf5dcb6-bd63-46ec-9b2a-0ff3abfc6ab8.jpg)

**Comment by yachen** [comment]
Yes it's normal. Your system boot into busybox shell.
