### ISSUE TITLE
env.txt not working on NUC980 IoT board

### ISSUE THREAD

**Issue by jaydcarlson** [OpenNuvoton/NUC980_NuWriter_CMD#3]
I'm trying to use NuWriter to load u-boot-spl, u-boot, uImage, and env.txt to my NUC980 IoT board, but I'm having issues getting the environmental variables working.

Here is my configuration:
```
image_num = 4
image0_path= /home/jay/NUC970_Buildroot/output/build/uboot-master/spl/u-boot-spl.bin
image0_type = loader
image0_exe_addr = 0x200
image0_start_offset = 0x00000

image1_type = data
image1_path= /home/jay/NUC970_Buildroot/output/images/u-boot.bin
image1_exe_addr = 0x00
image1_start_offset = 0x100000

image2_type = data
image2_path= /home/jay/NUC970_Buildroot/output/images/uImage
image2_exe_addr = 0x0000
image2_start_offset = 0x200000

image3_type = env
image3_path= /home/jay/NUC970_U-Boot_v2016.11/board/nuvoton/nuc980/nuc980_iot_env.txt
image3_exe_addr = 0x00000
image3_start_offset = 0x80000
```

Here are the contents of my nuc980_iot_env.txt file:
```
baudrate=115200
bootcmd=sf probe 0 75000000; sf read 0x7FC0 0x200000 0x800000; bootm 0x7FC0
bootdelay=3
stderr=serial
stdin=serial
stdout=serial
```
When I execute the flash utility, it says that both programming and verification succeeded, but when I reboot my board, my bootcmd is missing when I run `printenv`. I verified that `image3_start_offset` matches what's given in `nuc980_iot.h` in U-Boot.

Any ideas what's going on?

**Comment by yachen** [comment]
Hi,

Please pull 0bb8c86 and test again.

Sincerely,

Yi-An Chen

**Comment by jaydcarlson** [comment]
I tried the new version, but still no success. I stepped through the code and the ENV section is definitely getting hit, and it's sending this header:
```
flag: 0
filelen: 131072
no: 0
name: [0, 0, 0...]
type: 1
execaddr: 512
flashoffset: 524288
endaddr: 0
macaddr: [0, 0, 0...]
initSize: 0
```
lpBuffer has a small three-byte header, followed by the entire contents of my text file:
```
\212 \022 \254 baudrate=115200...
```
Any ideas?

**Comment by yachen** [comment]
Hi,

Please pull again. Thanks.


Sincerely,

Yi-An Chen

**Comment by jaydcarlson** [comment]
Sorry, I was away from the project for a while. Your changes fixed the problem! Thanks!
