### ISSUE TITLE
请问可以编译到NUC980上，做一个离线烧录器吗？

### ISSUE THREAD

**Issue by 1020165558** [OpenNuvoton/NUC980_NuWriter_CMD#4]
请问可以编译到NUC980上，做一个离线烧录器吗？

**Comment by yachen** [comment]
Hi, 

可以參考一下 https://github.com/OpenNuvoton/NUC980_SDWriter
980 由 SD 卡讀出資料, 燒錄到 SPI NOR/NAND 或 NAND flash.

Sincerely,

Yi-An Chen

**Comment by 1020165558** [comment]
980可以用sd更新，但是972没有sd启动，那在972能否实现离线烧录

**Comment by yachen** [comment]
沒有 SD boot, 所以只可以實現成 SPI NOR/eMMC/NAND 之間燒錄.

**Comment by 1020165558** [comment]
好的，谢谢
